services:

  app:
    image: goofolph/factorio
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 34197:34197/udp
      - 27015:27015/tcp
    volumes:
      - ${FACTORIO_DIR}:/factorio
    environment:
      - FACTORIO_DIR=${FACTORIO_DIR}
      - SERVER_SETTINGS=${SERVER_SETTINGS}
      - SAVE_NAME=${SAVE_NAME}
